 #include <iostream>
 using namespace std;
 int main()
 {
// //If we have to go to the next line we have to write ((endl or \n))
// cout<<"First Line"<<endl; 
// cout<<"Second Line"<<endl;
// //Arithematic Operators:::::::::::::
// cout << "The following are the type of Arithematic Operators" << endl;
// int a=25;
// int b=25;
// cout<<"The value of a+b is "<<a+b<<endl;
// cout<<"The value of a-b is "<<a-b<<endl;
// cout<<"The value of a/b is "<<a/b<<endl;
// cout<<"The value of a*b is "<<a*b<<endl;
// cout<<"The value of a%b is "<<a%b<<endl;
// cout<<"The value of a++ is "<<a++<<endl;
// cout<<"The value of a-- is "<<a--<<endl;
// cout<<"The value of ++a is "<<++a<<endl;
// cout<<"The value of --a is "<<--a<<endl;
// cout<<endl;

// //Assignment Operators  O/R  Comparision Operators::::::::::
// cout<<"The following are the type of Comparrision Operators"<<endl;
// cout<<"The value of a==b is "<<(a==b)<<endl;
// cout<<"The value of a!=b is "<<(a!=b)<<endl;
// cout<<"The value of a>b is "<<(a>b)<<endl;
// cout<<"The value of a<b is "<<(a<b)<<endl;
// cout<<"The value of a>=b is "<<(a>=b)<<endl;
// cout<<"The value of a=<b is "<<(a<=b)<<endl;


//Logical Operators::::::::::
// int a=4 ,b=7;
// cout << "The following are the type of Logical Operators" << endl;
// cout<<"The value of a=b and value of a>b is :<<(a==b)<<endl;
return 0;
 }